### ISSUE TITLE
Installation issue in redmine 3

### ISSUE THREAD

**Issue by Ajeeshb** [jbbarth/redmine_stronger#1]
My redmine Environment:

  Redmine version                3.3.1.stable
  Ruby version                   2.2.3-p173 (2015-08-18) [x86_64-linux]
  Rails version                  4.2.7.1
  Environment                    production
  Database adapter               Mysql2

plugins]# bundle exec rake redmine:plugins:migrate RAILS_ENV=production
(in /var/www/redmine-3.3.1)
/usr/local/rvm/gems/ruby-2.2.3/gems/htmlentities-4.3.1/lib/htmlentities/mappings/expanded.rb:465: warning: duplicated key at line 466 ignored: "inodot"
rake aborted!
Redmine::PluginNotFound: Redmine::PluginNotFound
/var/www/redmine-3.3.1/lib/redmine/plugin.rb:123:in `find'
/var/www/redmine-3.3.1/lib/redmine/plugin.rb:251:in `requires_redmine_plugin'
/var/www/redmine-3.3.1/plugins/redmine_stronger/init.rb:10:in `block in <top (required)>'
/var/www/redmine-3.3.1/lib/redmine/plugin.rb:75:in `instance_eval'
/var/www/redmine-3.3.1/lib/redmine/plugin.rb:75:in `register'
/var/www/redmine-3.3.1/plugins/redmine_stronger/init.rb:1:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.2.3/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
/usr/local/rvm/gems/ruby-2.2.3/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `block in require'
/usr/local/rvm/gems/ruby-2.2.3/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/local/rvm/gems/ruby-2.2.3/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
/var/www/redmine-3.3.1/lib/redmine/plugin.rb:155:in `block in load'
/var/www/redmine-3.3.1/lib/redmine/plugin.rb:146:in `each'
/var/www/redmine-3.3.1/lib/redmine/plugin.rb:146:in `load'
/var/www/redmine-3.3.1/config/initializers/30-redmine.rb:21:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.2.3/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `load'
/usr/local/rvm/gems/ruby-2.2.3/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `block in load'

**Comment by nanego** [comment]
I have updated the Readme. You can follow new instructions about the dependency to the Deface plugin : 
* install the redmine_base_deface plugin (see [here](https://github.com/jbbarth/redmine_base_deface))

**Comment by Ajeeshb** [comment]
Plugin needs mysql root access ? I am getting the following error message.

in /var/www/redmine-3.3.1)
/usr/local/rvm/gems/ruby-2.2.3/gems/htmlentities-4.3.1/lib/htmlentities/mappings/expanded.rb:465: warning: duplicated key at line 466 ignored: "inodot"
rake aborted!
Mysql2::Error: Access denied for user 'root'@'localhost' (using password: NO)
/usr/local/rvm/gems/ruby-2.2.3/gems/mysql2-0.3.21/lib/mysql2/client.rb:70:in `connect'

**Comment by nanego** [comment]
The plugin doesn't need it. But Redmine yes. Maybe you have to complete Redmine settings in database.yml.

**Comment by Ajeeshb** [comment]
Ah ok,
After executing the following command 
plugins]# rake redmine:plugins:migrate RAILS_ENV=production

Migrating redmine_base_deface (Redmine Base Deface plugin)...

Plugin is not showing in the redmine -> Administration -> Plugin

The steps I have done for installing the plugin.
1. Download to the plugin to plugin directory.
2. bundle install ( executed the command)
3. rake redmine:plugins:migrate RAILS_ENV=production

Do I need to execute the following command
bundle exec rake db:migrate RAILS_ENV=production
